services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    secrets:
      - curseforge_api_key_file
    environment:
      CurseForgeApiKeyFile: /run/secrets/curseforge_api_key_file
secrets:
  curseforge_api_key_file:
    file: curseforge_api_key.txt
